name: Deploy Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Project
        run: mvn clean package -DskipTests

      - name: Deploy and Restart
        run: |

          $ErrorActionPreference = "Stop"
          $jarFile = Get-ChildItem -Path target -Filter *.jar | Select-Object -First 1
          
          try {
              Stop-Process -Name "java" -Force
          } catch {
              Write-Output "Nenhuma aplicação Java estava rodando."
          }

          if ($null -ne $jarFile) {
              Write-Output "Arquivo .jar encontrado: $($jarFile.Name)"
              Write-Output "Iniciando aplicação em segundo plano..."
              
              Start-Process -FilePath "java" `
                            -ArgumentList "-jar $($jarFile.FullName)" `
                            -NoNewWindow `
                            -PassThru
              Write-Output "Aplicação iniciada com sucesso."
          } else {
              Write-Output "Erro: Nenhum arquivo .jar encontrado na pasta target."
              exit 1
          }
        shell: powershell
