name: Deploy Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    
      - name: Stop All Processes in Target
        run: |
          Stop-Process -Name "java.exe" -Force -ErrorAction SilentlyContinue
          Write-Output "Todos os processos relacionados ao Java foram encerrados."
        
        shell: powershell
        
      - name: Force Unlock File with Handle
        run: |
          # Identifica os processos que estão usando o arquivo
          $handleOutput = & $handleTool $filePath
          $processIds = $handleOutput | Select-String -Pattern 'PID: (\d+)' | ForEach-Object {
          ($_ -match 'PID: (\d+)') | Out-Null
          $Matches[1].Trim()
          }

          foreach ($processId in $processIds) {
          if ([int]::TryParse($processId, [ref]$null)) {  # Valida se é um inteiro
          Write-Output "Encerrando processo com PID: $processId"
          try {
            Stop-Process -Id ([int]$processId) -Force -ErrorAction Stop
            } catch {
            Write-Output "Erro ao encerrar o processo com PID: $processId. $_"
            }
          } else {
            Write-Output "PID inválido encontrado: $processId"
          }
          }

          Remove-Item -Path "C:\actions-runner\GisaAppliction\GisaAppliction\target" -Recurse -Force
          Write-Output "Arquivo e diretório removidos com sucesso."

        shell: powershell



      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Project
        run: mvn clean package -DskipTests

      - name: Deploy and Restart
        run: |

          $ErrorActionPreference = "Stop"
          $jarFile = Get-ChildItem -Path target -Filter *.jar | Select-Object -First 1
          
          try {
              Stop-Process -Name "java" -Force
          } catch {
              Write-Output "Nenhuma aplicação Java estava rodando."
          }

          if ($null -ne $jarFile) {
              Write-Output "Arquivo .jar encontrado: $($jarFile.Name)"
              Write-Output "Iniciando aplicação em segundo plano..."
              
              Start-Process -FilePath "java" `
                            -ArgumentList "-jar $($jarFile.FullName)" `
                            -NoNewWindow `
                            -PassThru
              Write-Output "Aplicação iniciada com sucesso."
          } else {
              Write-Output "Erro: Nenhum arquivo .jar encontrado na pasta target."
              exit 1
          }
        shell: powershell
