name: Deploy Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Stop Service and Kill Java
        run: |
          $ErrorActionPreference = "Continue"
          try {
              Stop-Service -Name "GisaApplicationService" -Force
              Write-Output "Serviço GisaApplicationService encerrado com sucesso."
          } catch {
              Write-Output "Serviço GisaApplicationService não estava em execução."
          }

          try {
              taskkill /F /IM java.exe
              Write-Output "Processos Java encerrados com sucesso."
          } catch {
              Write-Output "Nenhum processo Java estava em execução."
          }

          Remove-Item -Path "C:\actions-runner\GisaAppliction\GisaAppliction\target" -Recurse -Force
          Write-Output "Diretório target removido com sucesso."

          exit 0
        shell: powershell

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Project
        run: mvn clean package -DskipTests

      - name: Start Gisa Application Service
        run: |
          $ErrorActionPreference = "Stop"
          try {
              Start-Service -Name "GisaApplicationService"
              Write-Output "Serviço GisaApplicationService iniciado com sucesso."
          } catch {
              Write-Output "Erro ao iniciar o serviço GisaApplicationService."
              exit 1
          }
        shell: powershell
